/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile uint32_t vuint32;

#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800

#define RCC_APB2ENR *(vuint32 *)(RCC_BASE + 0x18)
#define GPIOA_CRH   *(vuint32 *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR   *(vuint32 *)(GPIOA_BASE + 0x0C)

#define RCC_IOPAEN (1<<2)
#define GPIOA13 (1<<13)

typedef union{
	vuint32 all_fields;

	struct {
		vuint32 :13;
		vuint32 p13:1;
	} Pin;

} Register_t;

int x = 6;

int main(void)
{
	RCC_APB2ENR |= RCC_IOPAEN;

	GPIOA_CRH &= (0xFF0FFFFF);
	GPIOA_CRH |= (0x00200000);

	volatile Register_t* R_ODR = (volatile Register_t*)(GPIOA_BASE + 0x0C);

	while(1){
		R_ODR->Pin.p13 = 1;
		for(int i = 0; i<100000; i++);

		R_ODR->Pin.p13 = 0;
		for(int i = 0; i<100000; i++);
	}

	return 0;

}
